src/App.js
src/Utils.js
src/components/Landing.css
src/components/Landing.js
src/index.js

Add period option to landing component

---

public/index.html
src/App.js
src/components/Landing.js

Added the tracking script to index.html and implemented tracking for Landing & App components.

Added analytics support

---

src/App.js
src/App.test.js

- Resolved issue #12 
- Added a 10-hit count to try and catch an English album name until finally fail with a suitable error message
- Added a mediocre test based on a user with a decent amount of Hebrew scrubbles (not a good test and not even deterministic, but it's something :| )

None english auto-win bug fix

---

src/components/Artwork.js

- Fixed #15 
- Artwork image is set to `draggable=False`
- <del>Right clicking was also prevented</del>

Artwork drag and drop fix

---

.gitignore
src/App.css
src/App.js
src/App.test.js
src/components/Artwork.js
src/components/Landing.css
src/components/Landing.js
src/index.js

- Resolves issue #11  
- Addes a "Hide artwork" option in landing.js
- Addes a "settings" link in the bottom of app.js to return back to change settings
- Replaces #13

Hide album artwork feature

---

package.json
src/utils/index.js
src/views/Game/Game.js
src/views/Landing/Landing.js
yarn.lock

Use [hangman-game-engine](https://github.com/guytepper/hangman-game-engine) as the game logic.

Switch to use hangman-game-engine

---

src/api/__mocks__/albumInfo.json
src/api/__mocks__/api.js
src/api/__mocks__/index.js
src/api/api.js
src/api/index.js
src/utils/index.js
src/views/Game/Game.js
src/views/Game/Game.test.js

Moved API calls from the `utils` file to an independent module.

Added API module

---

config-overrides.js
package.json
src/index.js
yarn.lock

Added hot module replacement integration to `create-react-app`.  
[More info](https://daveceddia.com/hot-reloading-create-react-app/)

Added Hot Module Replacement

---

src/components/Artwork/Artwork.js
src/views/Game/Game.js

Reduce the blurriness of the hidden artwork.

Reduce artwork blur level

---

package.json
src/api/api.js
yarn.lock

Remove descriptors from the album name, e.g. `Nevermind (Remastered) -> Nevermind`.

Remove album name descriptors

---

src/api/api.js
src/views/Game/Game.js

Changed from retrieving 50 albums to retrieving up to 1000 albums.

Retrieve up to 1000 user saved albums 

---

src/components/Keyboard/Keyboard.css
src/components/Keyboard/Keyboard.js
src/components/Keyboard/Keyboard.test.js
src/index.css
src/views/Game/Game.js

* Changed button colors
* Button letter color is changed upon guessing
* Increased font size
* Increased button size on larger viewports
* Added tests
**Before**
**After**

Keyboard improvements

---

src/components/Keyboard/Keyboard.css
src/components/Keyboard/Keyboard.js
src/components/Keyboard/Keyboard.test.js
src/views/Game/Game.css

Changed keyboard to QWERTY layout

---

src/components/LoginButton/LoginButton.css
src/components/LoginButton/LoginButton.js
src/components/LoginButton/LoginButton.stories.js
src/components/LoginButton/index.js

Added login button component

---

src/components/GameHeader/GameHeader.css
src/components/GameHeader/GameHeader.js
src/components/GameHeader/GameHeader.stories.js
src/components/GameHeader/index.js
src/views/Game/Game.css
src/views/Game/Game.js

Added game header component

---

.storybook/preview-head.html
public/index.html
src/components/Button/Button.css
src/components/Button/Button.js
src/components/Button/Button.stories.js
src/components/GameHeader/GameHeader.js
src/components/SettingsModal/SettingsModal.css
src/components/SettingsModal/SettingsModal.js
src/components/SettingsModal/SettingsModal.stories.js
src/components/SettingsModal/index.js
src/views/Game/Game.css
src/views/Game/Game.js

Added settings modal

---

src/api/api.js
src/components/GameHeader/GameHeader.css
src/components/Keyboard/Keyboard.css
src/components/Progress/Progress.css
src/components/Progress/Progress.js
src/components/Progress/Progress.test.js
src/utils/Utils.test.js
src/utils/index.js
src/views/Game/Game.js
src/views/Landing/Landing.css

Display the total albums and the guessed albums correctly (currently shows static numbers).

Album progress implementation

---

public/delete.svg
src/components/Hearts/Hearts.css
src/components/Hearts/Hearts.js
src/components/Hearts/Hearts.test.js

Change hearts color to grey on wrong guess

---

package.json
src/components/Button/Button.js
src/components/Hearts/Hearts.js
src/components/Modal/Modal.js
yarn.lock

Use classnames package to calculate class names

---

src/utils/Utils.test.js
src/utils/index.js
src/views/Game/Game.js
src/views/Game/Game.test.js

`event.key` caused some issues for non qwerty keyboard layouts (also it's deprecated so buhh)

Change usage of event.which to event.key

---

src/components/GameHeader/GameHeader.css

Changed game top bar to use CSS grid layout instead of flex - if the browser supports it. 
This will increase the component layout accuracy.

Added grid layout support for GameHeader
